### ISSUE TITLE
Can we limit when this plugin runs?

### ISSUE THREAD

**Issue by seanforyou23** [rh-uxd/patternfly-snippets#9]
Hello, lovely plugin! I've been using it, and so far it has been working like a charm every time I've needed it! One thing I notice is that it even works like a charm when I don't need it 😄for example, in a few situations I see the dropdown pops up unexpectedly and I find myself having to ctrl+z to back out an accidental code snippet. 

<img width="539" alt="Screen Shot 2020-02-21 at 9 33 09 AM" src="https://user-images.githubusercontent.com/5942899/75043196-a5fa7d00-548d-11ea-9213-3ac2b5d4c8f9.png">

For example, in the above screenshot, notice I'm just typing into a scratch text file - maybe, in this case, the IntelliSense shouldn't display? When I'm developing a PF project it's really not a problem, but when it happens outside of a JS/TS file altogether it could be perceived as a little jarring.

Is there any way to limit the scope of when this runs, like maybe when you're inside a JSX fragment or something? No idea what's capable, but figured I'd ask. Thanks!

**Comment by dgutride** [comment]
@seanforyou23  - I thought @jschuler said we could target specific file types with the snippets, that seems like a good adjustment.

**Comment by jschuler** [comment]
Yes it's a little trigger happy right now, I am making adjustments currently, there should be an update out soon, thanks!

**Comment by jschuler** [comment]
@seanforyou23 The extension has been updated to 0.1.1. (https://marketplace.visualstudio.com/items/PatternFly.patternfly-snippets/changelog) VSCode should auto-detect if there is an extension update at some point, or you can manually trigger it. Thanks for reporting the issue!

<img width="560" alt="Screen Shot 2020-02-21 at 1 39 08 PM" src="https://user-images.githubusercontent.com/869106/75062955-c9372380-54b1-11ea-978b-8512643c3414.png">
